# Generated by Django 4.0.2 on 2022-04-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dars', models.CharField(max_length=255)),
                ('akharin_nomre', models.FloatField()),
                ('code_standard', models.IntegerField()),
                ('noe_dars', models.CharField(max_length=255)),
                ('vahed_teori', models.IntegerField()),
                ('vahed_amali', models.IntegerField()),
                ('saat_teori', models.IntegerField()),
                ('saat_amali', models.IntegerField()),
                ('pish_niaz', models.CharField(max_length=255)),
                ('code_pish_niaz', models.IntegerField()),
            ],
        ),
    ]
