# Generated by Django 3.2.12 on 2022-04-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_alter_newapp_akharin_nomre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newapp',
            name='akharin_nomre',
            field=models.FloatField(blank=True, null=True, verbose_name='آخرين نمره'),
        ),
        migrations.AlterField(
            model_name='newapp',
            name='code_pish_niaz',
            field=models.IntegerField(blank=True, null=True, verbose_name='کد پيش نيازها'),
        ),
        migrations.AlterField(
            model_name='newapp',
            name='code_standard',
            field=models.IntegerField(blank=True, null=True, verbose_name='کد استاندارد'),
        ),
        migrations.AlterField(
            model_name='newapp',
            name='dars',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='درس'),
        ),
        migrations.AlterField(
            model_name='newapp',
            name='noe_dars',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع درس'),
        ),
        migrations.AlterField(
            model_name='newapp',
            name='pish_niaz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='پيش نيازها'),
        ),
        migrations.AlterField(
            model_name='newapp',
            name='saat_amali',
            field=models.IntegerField(blank=True, null=True, verbose_name='ساعت عملي'),
        ),
        migrations.AlterField(
            model_name='newapp',
            name='saat_teori',
            field=models.IntegerField(blank=True, null=True, verbose_name='ساعت تئوري'),
        ),
        migrations.AlterField(
            model_name='newapp',
            name='vahed_amali',
            field=models.IntegerField(blank=True, null=True, verbose_name='واحد عملي'),
        ),
        migrations.AlterField(
            model_name='newapp',
            name='vahed_teori',
            field=models.IntegerField(blank=True, null=True, verbose_name='واحد تئوري'),
        ),
    ]
