# Generated by Django 3.2.12 on 2022-04-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_alter_newapp_code_pish_niaz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newapp',
            name='code_pish_niaz',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True, verbose_name='کد پيش نيازها'),
        ),
    ]
