# Generated by Django 3.2.12 on 2022-04-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_alter_newapp_code_pish_niaz'),
    ]

    operations = [
        migrations.CreateModel(
            name='daneshjo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shomare_daneshjoi', models.IntegerField(blank=True, null=True, verbose_name='شماره دانشجويي')),
                ('code_meli', models.CharField(blank=True, default='', max_length=255, verbose_name='کد ملي')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام')),
                ('daneshkade', models.CharField(blank=True, max_length=255, null=True, verbose_name='دانشکده')),
                ('reshte', models.CharField(blank=True, max_length=255, null=True, verbose_name='رشته')),
                ('maqta', models.CharField(blank=True, max_length=255, null=True, verbose_name='مقطع')),
                ('nobat_paziresh', models.CharField(blank=True, max_length=255, null=True, verbose_name='نوبت پذيرش')),
                ('term_vorood', models.IntegerField(blank=True, null=True, verbose_name='ترم ورود')),
                ('nam_pedar', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام پدر')),
                ('tarikh_tavalod', models.DateField(blank=True, null=True, verbose_name='تاريخ تولد')),
            ],
        ),
    ]
