# Generated by Django 3.2.12 on 2022-04-16 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_daneshjo'),
    ]

    operations = [
        migrations.AddField(
            model_name='daneshjo',
            name='newapp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.newapp'),
        ),
    ]
