# Generated by Django 3.2.12 on 2022-04-16 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_daneshjo_newapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daneshjo',
            name='newapp',
        ),
    ]
