# Generated by Django 3.2.12 on 2022-04-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0010_remove_daneshjo_newapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daneshjo',
            name='tarikh_tavalod',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='تاريخ تولد'),
        ),
    ]
