# Generated by Django 3.2.12 on 2022-04-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0012_info_dars'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_dars',
            name='dars',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='درس'),
        ),
    ]
