# Generated by Django 3.2.12 on 2022-04-17 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0014_auto_20220418_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info_dars',
            name='id',
        ),
        migrations.RemoveField(
            model_name='info_dars',
            name='info',
        ),
        migrations.AlterField(
            model_name='info_dars',
            name='dars',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='newapp.newapp'),
        ),
    ]
