# Generated by Django 3.2.12 on 2022-05-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0015_auto_20220418_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_dars',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='info_dars',
            name='dars',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='درس'),
        ),
    ]
