# Generated by Django 3.2.12 on 2022-05-01 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0016_auto_20220501_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info_dars',
            name='dars',
        ),
    ]
