# Generated by Django 3.2.12 on 2022-05-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0017_remove_info_dars_dars'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newapp',
        ),
        migrations.AddField(
            model_name='info_dars',
            name='akharin_nomre',
            field=models.FloatField(blank=True, null=True, verbose_name='آخرين نمره'),
        ),
        migrations.AddField(
            model_name='info_dars',
            name='code_pish_niaz',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='کد پيش نيازها'),
        ),
        migrations.AddField(
            model_name='info_dars',
            name='code_standard',
            field=models.IntegerField(blank=True, null=True, verbose_name='کد استاندارد'),
        ),
        migrations.AddField(
            model_name='info_dars',
            name='dars',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='درس'),
        ),
        migrations.AddField(
            model_name='info_dars',
            name='noe_dars',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع درس'),
        ),
        migrations.AddField(
            model_name='info_dars',
            name='pish_niaz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='پيش نيازها'),
        ),
        migrations.AddField(
            model_name='info_dars',
            name='saat_amali',
            field=models.IntegerField(blank=True, null=True, verbose_name='ساعت عملي'),
        ),
        migrations.AddField(
            model_name='info_dars',
            name='saat_teori',
            field=models.IntegerField(blank=True, null=True, verbose_name='ساعت تئوري'),
        ),
        migrations.AddField(
            model_name='info_dars',
            name='vahed_amali',
            field=models.IntegerField(blank=True, null=True, verbose_name='واحد عملي'),
        ),
        migrations.AddField(
            model_name='info_dars',
            name='vahed_teori',
            field=models.IntegerField(blank=True, null=True, verbose_name='واحد تئوري'),
        ),
    ]
