# Generated by Django 3.2.12 on 2022-05-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0018_auto_20220502_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='newapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dars', models.CharField(blank=True, max_length=255, null=True, verbose_name='درس')),
                ('akharin_nomre', models.FloatField(blank=True, null=True, verbose_name='آخرين نمره')),
                ('code_standard', models.IntegerField(blank=True, null=True, verbose_name='کد استاندارد')),
                ('noe_dars', models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع درس')),
                ('vahed_teori', models.IntegerField(blank=True, null=True, verbose_name='واحد تئوري')),
                ('vahed_amali', models.IntegerField(blank=True, null=True, verbose_name='واحد عملي')),
                ('saat_teori', models.IntegerField(blank=True, null=True, verbose_name='ساعت تئوري')),
                ('saat_amali', models.IntegerField(blank=True, null=True, verbose_name='ساعت عملي')),
                ('pish_niaz', models.CharField(blank=True, max_length=255, null=True, verbose_name='پيش نيازها')),
                ('code_pish_niaz', models.SlugField(blank=True, max_length=200, null=True, verbose_name='کد پيش نيازها')),
            ],
        ),
        migrations.RemoveField(
            model_name='info_dars',
            name='akharin_nomre',
        ),
        migrations.RemoveField(
            model_name='info_dars',
            name='code_pish_niaz',
        ),
        migrations.RemoveField(
            model_name='info_dars',
            name='code_standard',
        ),
        migrations.RemoveField(
            model_name='info_dars',
            name='noe_dars',
        ),
        migrations.RemoveField(
            model_name='info_dars',
            name='pish_niaz',
        ),
        migrations.RemoveField(
            model_name='info_dars',
            name='saat_amali',
        ),
        migrations.RemoveField(
            model_name='info_dars',
            name='saat_teori',
        ),
        migrations.RemoveField(
            model_name='info_dars',
            name='vahed_amali',
        ),
        migrations.RemoveField(
            model_name='info_dars',
            name='vahed_teori',
        ),
    ]
