# Generated by Django 3.2.12 on 2022-06-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0019_auto_20220502_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daneshjo',
            name='shomare_daneshjoi',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='شماره دانشجويي'),
        ),
        migrations.AlterField(
            model_name='daneshjo',
            name='term_vorood',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ترم ورود'),
        ),
        migrations.AlterField(
            model_name='newapp',
            name='akharin_nomre',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='آخرين نمره'),
        ),
        migrations.AlterField(
            model_name='newapp',
            name='code_pish_niaz',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='کد پيش نيازها'),
        ),
        migrations.AlterField(
            model_name='newapp',
            name='code_standard',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='کد استاندارد'),
        ),
        migrations.AlterField(
            model_name='newapp',
            name='saat_amali',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ساعت عملي'),
        ),
        migrations.AlterField(
            model_name='newapp',
            name='saat_teori',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ساعت تئوري'),
        ),
        migrations.AlterField(
            model_name='newapp',
            name='vahed_amali',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='واحد عملي'),
        ),
        migrations.AlterField(
            model_name='newapp',
            name='vahed_teori',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='واحد تئوري'),
        ),
    ]
